### ISSUE TITLE
How to verify/acknowledge purchases for android billing 3.0?

### ISSUE THREAD

**Issue by naumanmunir** [EmilAlipiev/XFInAppBilling#14]

**Comment by EmilAlipiev** [comment]
Library handles it for you on PurchaseResult if acknowledgement will fail, you can call GetPurchases function to re-try to acknowledge each pending purchase with IsAcknowledge=false.

**Comment by EmilAlipiev** [comment]
just closing this because if you check the [documentation ](https://developer.android.com/google/play/billing/integrate#process)and OnPurchasesUpdated function in Android.cs, package is doing exactly how it is suggested in the android documentation. After a purchase completed, each purchase is verified with purchase.IsAcknowledged (NotifyFullFillmentAsync function), if it is false, it sends an acknowledge request. if you any problem or further question, please let me know.
