### ISSUE TITLE
Setup help

### ISSUE THREAD

**Issue by ja179053** [EmilAlipiev/XFInAppBilling#24]
Sorry for not understanding but I have no idea how to get started, what libraries to use or how to call the purchase code

**Comment by EmilAlipiev** [comment]
you start calling with `await CrossXFInAppBilling.Current.ConnectAsync()` this will start a connection and then you can call the functions you need. if you need to get products and subscriptions `await   CrossXFInAppBilling.Current.GetProductsAsync` 
if you need to do a purchase, you call `await   CrossXFInAppBilling.Current.PurchaseAsync` functions. That simple but of course you need to read through the docuementations of each platform from Google, Apple and Microsoft to understand how to do set up and how it works.

More i cannot help you because in app purchasing is a big thing and requires a lot of studying to understand how google and apple works.
