### ISSUE TITLE
Dependency to UWP on every project?

### ISSUE THREAD

**Issue by Sebastian1989101** [EmilAlipiev/XFInAppBilling#8]
Why is there (based on the Nuget site) a reference to UWP even for iOS and Android?

**Comment by EmilAlipiev** [comment]
where do you see that? can you be more specific?

**Comment by EmilAlipiev** [comment]
Nuget shows this. I dont see any Uwp reference on Ios and Android

![image](https://user-images.githubusercontent.com/10422347/90817108-9c16e100-e32d-11ea-9a89-a1ab83687d9a.png)

**Comment by Sebastian1989101** [comment]
Right here: 
![chrome_2020-08-20_21-45-33](https://user-images.githubusercontent.com/25636075/90818359-ab4a5e80-e32e-11ea-8ffc-6267b6d539b3.png)

https://www.nuget.org/packages/XFInAppBilling/2.0.1-beta

For 2.0.1-beta of this plugin it has UWP in every project type reference on nuget.org.

**Comment by EmilAlipiev** [comment]
Ops. i haven't recognized on beta. just fixed it. it should be caused by update when using package manager UI. i think this is the bad side of multi targeting projects, it needs to be updated manually in the code, not using UI. otherwise it updates for all and changes references. Thanks for finding out this. I have just pushed a new version with the fix. (although it was not causing any error and probably linkers on ios and android were removing it)
new version should be on nuget available in 10-15 mins.

**Comment by EmilAlipiev** [comment]
2.0.2-beta released now it looks good to me.
